on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Git environment
        uses: actions4git/setup-git@v1.0.3
        with:
          user: 'me'
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: 'MC Publish'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: McLbj2dz
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          curseforge-id: 960132
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
